DEFINE VARIABLE c-lin AS CHARACTER FORMAT "x(80)"  NO-UNDO.
DEFINE VARIABLE c-arq AS CHARACTER   NO-UNDO.

ASSIGN CURRENT-WINDOW:WIDTH = 120
       c-arq = "c:\treina\testeImport.p".

INPUT FROM value(c-arq).
REPEAT:
    IMPORT UNFORMATTED c-lin.
    DISP c-lin WITH FRAME f-dados WIDTH 100 DOWN.
END.
INPUT CLOSE.
