MESSAGE 1 TRANSACTION
    VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.

DO TRANSACTION:
    FIND FIRST order exclusive-lock.     
END.

DO TRANSACTION:
    FIND FIRST customer NO-LOCK NO-ERROR.

    MESSAGE 2 TRANSACTION
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
END.

